---
kind: pipeline
type: kubernetes
name: magic-mirror-rpi-zero

platform:
  os: linux
  arch: aarch

trigger:
  branches:
    - master
  event:
    - push
    - tag

steps:
  - name: pi-gen
    image: zebardy/drone_pi-gen
    privileged: true
    volumes:
    - name: apt-cache
      path: /apt-cache
    - name: drone-output
      path: ${DRONE_WORKSPACE}/output
    settings:
      first_user_pass: raspberry
      disable_first_boot_user_rename: 1
      enable_ssh: 1
      target_hostname: magic-mirror
      pubkey_ssh_first_user: 
        from_secret: ssh_public_key
      pubkey_only_ssh: 1
      pi_gen_dir: pi-gen
      use_qcow2: 1
      pigen_docker_opts: "-v /apt-cache:/var/cache/apt"
  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_release_token
      base_url: 
        from_secret: gitea_url
      files: 
        - deploy/*.zip
        - deploy/*.info
        - deploy/build.log
    when:
      event: tag

volumes:
- name: apt-cache
  claim:
    name: apt-cache
    read_only: false
- name: drone-output
  host:
    path: /var/lib/cache
